### ISSUE TITLE
Разобраться с хранением и получением IP-адресов и UDP порта

### ISSUE THREAD

**Issue by yevsyukof** [zakne/p2p-network#5]
А именно реализовать классы IPv4Address и UdpPort. 
PS: Насколько я знаю в жабе есть класс для работы с IPv4-адресами (Inet4Address). Нужно понять насколько они применимы в Kotlin Native

**Comment by nonam3e** [comment]
https://developer.android.com/reference/kotlin/java/net/Inet4Address
Вроде как всё должно работать оттуда
